### ISSUE TITLE
File "build/bdist.linux-x86_64/egg/mininet/ns3.py", line 40, in <module>

### ISSUE THREAD

**Issue by prabhjotbatth** [dlinknctu/OpenNet#27]
Traceback (most recent call last):
  File "wifiroaming.py", line 14, in <module>
    import mininet.ns3
  File "build/bdist.linux-x86_64/egg/mininet/ns3.py", line 40, in <module>
ImportError: No module named ns.core

**Comment by pichuang** [comment]
hi, I'm try to install OpenNet in the morning, it work fine for me.
Could you please give me some more information? like "locate ns3.py"

**Comment by rascov** [comment]
Could you also provide detail about how you run the 'wifiroaming.py'
Have you run it in waf environment?
