### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by PhDstudent26** [dlinknctu/OpenNet#67]
Good afternoon,
I tried ti install OpenNet according to the instructions that I found in https://github.com/dlinknctu/OpenNet  
When I tried the command # python wifiroaming.py, I had the following error:

*** Adding controller
Unable to contact the remote controller at 127.0.0.1:6633
Traceback (most recent call last):
  File "wifiroaming.py", line 208, in <module>
    WifiNet()
  File "wifiroaming.py", line 168, in WifiNet
    net.addLink( clnode1, clnode2 )
  File "build/bdist.linux-i686/egg/mininet/net.py", line 393, in addLink
  File "build/bdist.linux-i686/egg/mininet/link.py", line 424, in __init__
  File "build/bdist.linux-i686/egg/mininet/link.py", line 468, in makeIntfPair
  File "build/bdist.linux-i686/egg/mininet/util.py", line 194, in makeIntfPair
Exception: Error creating interface pair (s1-eth2,s2-eth2): RTNETLINK answers: File exists

can you please help me to correct the problem (the ns-3 version is 3.22 and mininet version is 2.2.1 as mentioned in the file install.sh)

**Comment by pichuang** [comment]
hi,

please use "mn -c" and start your controller 

thanks

**Comment by PhDstudent26** [comment]
hi, 
Thank you for the response.
I used mn -c then # python wifiroaming.py, I fhad the following message:
*** Adding controller
Unable to contact the remote controller at 127.0.0.1:6633
Traceback (most recent call last):
  File "wifiroaming.py", line 208, in <module>
    WifiNet()
  File "wifiroaming.py", line 168, in WifiNet
    net.addLink( clnode1, clnode2 )
  File "build/bdist.linux-i686/egg/mininet/net.py", line 393, in addLink
  File "build/bdist.linux-i686/egg/mininet/link.py", line 424, in __init__
  File "build/bdist.linux-i686/egg/mininet/link.py", line 468, in makeIntfPair
  File "build/bdist.linux-i686/egg/mininet/util.py", line 194, in makeIntfPair
Exception: Error creating interface pair (s1-eth2,s2-eth2): RTNETLINK answers: File exists

**Comment by PhDstudent26** [comment]
Hi, 
Thank you for the response.
I used mn -c then python wifiroaming.py I had the following message:
Unable to contact the remote controller at 127.0.0.1:6633
Wifi pcap path: /tmp/pcap/wifi
CSMA pcap path:/tmp/pcap/csma
Netanim path: /tmp/xml/wifi-wired-bridged4.xml
*** Starting network
*** Configuring hosts
h1 h2 
*** Starting controller
c0 
*** Starting 7 switches
s1 s2 s3 s4 s5 s6 s7 ...
Testing network connectivity
*** h1 : ('ping 10.10.10.2 -c 3',)
PING 10.10.10.2 (10.10.10.2) 56(84) bytes of data.
From 10.10.10.1 icmp_seq=1 Destination Host Unreachable
From 10.10.10.1 icmp_seq=2 Destination Host Unreachable
From 10.10.10.1 icmp_seq=3 Destination Host Unreachable

--- 10.10.10.2 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2008ms
pipe 3
*** Starting CLI:
opennet> Max Packets per trace file exceeded

**Comment by pichuang** [comment]
hi,

`Unable to contact the remote controller at 127.0.0.1:6633`

You need to start your own controller. OpenNet didn't handle sdn controller.

**Comment by PhDstudent26** [comment]
hi, 
Can you please tell me how can I start my own controller?

**Comment by pichuang** [comment]
Suggest you to see [sdnds-tw/ryuInstallHelper](https://github.com/sdnds-tw/ryuInstallHelper)
It's easy to use.

**Comment by PhDstudent26** [comment]
thank you for your help. Unfortunately, I tried the two ways to install ryu but always there was errors. I want to know why it is necessary to have my own controller to run openNet
