### ISSUE TITLE
problem with binding python

### ISSUE THREAD

**Issue by nasrin-seifi** [dlinknctu/OpenNet#93]
Hi,
Could you do me a favor? I'm beginner in ns3 and opennet, first i read tutorial and step by step installed every requirements after that by using tarball downloaded and build and configure ns3.25.
when bind pygccxml, I receive this message:

mininet@ubuntu:~/ns-allinone-3.25/ns-3.25$ ./waf --pyrun examples/wireless/mixed-wireless.py
Waf: Entering directory `/home/mininet/ns-allinone-3.25/ns-3.25/build'
[ 296/1851] Processing command (${PYTHON}): ../bindings/python/ns3modulegen-modular.py ../src/internet/bindings/modulegen__gcc_ILP32.py -> src/internet/bindings/ns3module.cc src/internet/bindings/ns3module.h src/internet/bindings/ns3modulegen.log

Waf: Leaving directory `/home/mininet/ns-allinone-3.25/ns-3.25/build'
Build failed
 -> task in 'pybindgen(ns3 module internet)' failed (exit status 1): 
	{task 3064338124L: command_task ns3modulegen-modular.py,modulegen__gcc_ILP32.py -> ns3module.cc,ns3module.h,ns3modulegen.log}
''

when I use opennet again there is problem:

root@ubuntu:~/OpenNet/mininet-patch/examples/opennet# python wifiroaming.py 
Traceback (most recent call last):
  File "wifiroaming.py", line 14, in <module>
    import mininet.ns3
  File "build/bdist.linux-i686/egg/mininet/ns3.py", line 40, in <module>
ImportError: No module named ns.core

"mininet" and after that "mininet-ns3 integration" was installed.

Thanks in advance.

**Comment by kansokusha** [comment]
The example script, wifiroaming.py, only works with complete OpenNet installation.

It seems that your OpenNet have not be installed properly.
Please follow instructions in README to install OpenNet.

Current OpenNet only support NS-3.22.
So, we will not give comments about other version of NS-3.

**Comment by nasrin-seifi** [comment]
Hi,
could you help me? my problem didn't solve yet.
I didn't receive this message "OpenNet installation has completed." after installing opennet, in other hands this is mine:
Processing triggers for libc-bin (2.19-0ubuntu6) ...
***creating key pair
***configuring host
***copying public key to master
# master SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7
# master SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7
root@master's password:
root@ubuntu:~/OpenNet# 

root@ubuntu:~/OpenNet/mininet-patch/examples/opennet# python wifiroaming.py 
Traceback (most recent call last):
  File "wifiroaming.py", line 14, in <module>
    import mininet.ns3
  File "build/bdist.linux-i686/egg/mininet/ns3.py", line 

40, in <module>
ImportError: No module named ns.core

again I can't run "wifiroaming.py" program, but ns and mininet work together properly:
mininet@ubuntu:~/ns-allinone-3.22/ns-3.22$ sudo ./waf  --pyrun '/home/mininet/mininet/examples/ns3/wifi-ap.py' 
Waf: Entering directory `/home/mininet/ns-allinone-

3.22/ns-3.22/build'
Waf: Leaving directory `/home/mininet/ns-allinone-

3.22/ns-3.22/build'
'build' finished successfully (2.314s)

Modules built:
antenna    aodv   applications  bridge   buildings   config-store   core  csma   csma-layout              
dsdv     dsr    energy    fd-net-device       flow-monitor    internet    lr-wpan         lte        mesh   mobility      mpi    netanim (no Python)   network       nix-vector-routing        olsr 
point-to-point       point-to-point-layout     propagation   sixlowpan         spectrum      stats                    
tap-bridge                test (no Python)    topology-read   uan         virtual-net-device        wave  
wifi       wimax    
Modules not built (see ns-3 tutorial for explanation):
brite             click      openflow   visualizer               

*** ns-3 network demo
*** Creating Network
*** Configuring hosts
*** Network state:
h0
h1
h2
*** Running test
*** h0 : ('ping -c1 192.168.123.2',)
PING 192.168.123.2 (192.168.123.2) 56(84) bytes of data.

--- 192.168.123.2 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, 

time 0ms

*** h0 : ('ping -c1 192.168.123.3',)
PING 192.168.123.3 (192.168.123.3) 56(84) bytes of data.

--- 192.168.123.3 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, 

time 0ms

*** Starting CLI:
mininet> 

what's the solution?

Thanks in advance.

**Comment by nasrin-seifi** [comment]
Hi,
could you help me? my problem didn't solve yet.
I didn't receive this message "OpenNet installation has completed." after installing opennet, in other hands this is mine:
Processing triggers for libc-bin (2.19-0ubuntu6) ...
***creating key pair
***configuring host
***copying public key to master
master SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7
master SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7
root@master's password:
root@ubuntu:~/OpenNet# 

root@ubuntu:~/OpenNet/mininet-patch/examples/opennet# python wifiroaming.py 
Traceback (most recent call last):
  File "wifiroaming.py", line 14, in <module>
    import mininet.ns3
  File "build/bdist.linux-i686/egg/mininet/ns3.py", line 

40, in <module>
ImportError: No module named ns.core

again I can't run "wifiroaming.py" program, but ns and mininet work together properly:
mininet@ubuntu:~/ns-allinone-3.22/ns-3.22$ sudo ./waf  --pyrun '/home/mininet/mininet/examples/ns3/wifi-ap.py' 
Waf: Entering directory `/home/mininet/ns-allinone-

3.22/ns-3.22/build'
Waf: Leaving directory `/home/mininet/ns-allinone-

3.22/ns-3.22/build'
'build' finished successfully (2.314s)

Modules built:
antenna    aodv   applications  bridge   buildings   config-store   core  csma   csma-layout              
dsdv     dsr    energy    fd-net-device       flow-monitor    internet    lr-wpan         lte        mesh   mobility      mpi    netanim (no Python)   network       nix-vector-routing        olsr 
point-to-point       point-to-point-layout     propagation   sixlowpan         spectrum      stats                    
tap-bridge                test (no Python)    topology-read   uan         virtual-net-device        wave  
wifi       wimax    
Modules not built (see ns-3 tutorial for explanation):
brite             click      openflow   visualizer               

*** ns-3 network demo
*** Creating Network
*** Configuring hosts
*** Network state:
h0
h1
h2
*** Running test
*** h0 : ('ping -c1 192.168.123.2',)
PING 192.168.123.2 (192.168.123.2) 56(84) bytes of data.

--- 192.168.123.2 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, 

time 0ms

*** h0 : ('ping -c1 192.168.123.3',)
PING 192.168.123.3 (192.168.123.3) 56(84) bytes of data.

--- 192.168.123.3 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, 

time 0ms

*** Starting CLI:
mininet> 

what's the solution?

Thanks in advance.

**Comment by kansokusha** [comment]
It seems that you have still not completed the installation yet.
If you use our installation script, the parent directory of ns-allinone-3.22 should be OpenNet.

There is a quick work-around for your environment:
1. cd ~/ns-allinone-3.22/ns-3.22
2. ./waf install
Above instructions should can solve import error of ns.core.

But without complete installation, there may be other issues.

**Comment by nasrin-seifi** [comment]
Hi,
thank you for your response, but after applying ./waf install I receive another error:

root@ubuntu:~/OpenNet/mininet-patch/examples/opennet# python wifiroaming.py 
Traceback (most recent call last):
  File "wifiroaming.py", line 14, in <module>
    import mininet.ns3
  File "build/bdist.linux-i686/egg/mininet/ns3.py", line 40, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ns/core.py", line 5, in <module>
    from . import _core
ImportError: libns3.22-core-debug.so: cannot open shared  object file: No such file or directory

I tried to install opennet again but it seems don't work. Do you know another repository of OpenNet?

Thanks.

**Comment by kansokusha** [comment]
This is the main repository of OpenNet.

Please type follow command in directory of ns-3.22: ./waf configure
This command will configure the building target of ns-3.22.

Please ensure the status of following options are enabled.
Python Bindings                        : enabled
Python API Scanning Support   : enabled

One major purpose of our installation script is make sure above options are enabled.

If these options can not be enabled, means your environment have not be configured correctly.

Please follow below steps to setup OpenNet:
1. Remove all files and directories under /tmp
2. Remove directory of OpenNet
3. Remove directories of NS-3 and Mininet

4. Open a new terminal and type: sudo su -
5. apt-get install git ssh
6. git clone https://github.com/dlinknctu/OpenNet.git
7. cd OpenNet
8. ./configure.sh
9. ./install.sh master
10. Wait until the terminal prints "OpenNet installation has completed."

11. git clone https://github.com/noxrepo/pox.git
12. cd pox
13. ./pox.py forwarding.l2_learning &
14. cd ../mininet/examples/opennet
15. python wifiroaming.py

Please do not try to run the example script without complete installation.
And please run the example script under mininet/examples, not mininet-patch/examples.

If still encounter issues, please screen-shot the error message.
Error messages without proper composing are difficult to understand.

**Comment by nasrin-seifi** [comment]
I'm really appreciate for your response.
they are enable and there isn't any problem between mininet and ns3, I can run any *.py from mininet with ns3 command. "sudo ./waf --pyrun *.py"

please take look at https://github.com/dlinknctu/OpenNet I try to install it with your instruction but no difference in result even in an empty ubuntu I try to obtain successfully installed but it is impossible.
another thing is, there is NOT any address like "/mininet/examples/opennet" you can see it in current repository that just contain "mininet-patch/examples/opennet".

![Uploading Screenshot from 2016-07-09 12^%25^%54.png…]()
![Uploading Screenshot from 2016-07-09 12^%26^%28.png…]()

Thanks a lot.

**Comment by kansokusha** [comment]
It seems that the problem is at SSH key deployment.

Below screen-shot shows SSH key deployment progress of OpenNet, on a new Ubuntu VM:
![ssh-deployment](https://cloud.githubusercontent.com/assets/2024544/16712657/80ff0644-46c0-11e6-86b3-14d67517b663.PNG)

At the step of "***copying public key to master", there should not acquire password from user.

Please switch to root via "sudo su -", then type the following commands:
1. ssh-keyscan -H master >> /root/.ssh/known_hosts
2. ssh-copy-id -i /root/.ssh/cluster_key.pub root@master &> /dev/null

Then change the directory to OpenNet and try to run ./install.sh master again.
The installation script should work.

**Comment by nismyi** [comment]
Hi there,
Are all theses NS3 and  mininet source codes should be inside the OpenNet Directory?
Which one I should install first NS3 or Mininet?

Thank you

**Comment by kansokusha** [comment]
"Directory of source code" and "sequence of installation" are not matter,  both NS-3 and Mininet should be installed in Linux libraries.

For NS-3, in ns-allinone-3.22/ns-3.22:

    ./waf build
    ./waf install

For Mininet, in mininet/util:

    ./install.sh -n

**Comment by nismyi** [comment]
Thank you, but I don't understand why I am having this hangout.
When I try to use this command in ns-allinone-3.22: ./build.py --enable-example --enable-tests
![ns3_build](https://cloud.githubusercontent.com/assets/12607907/18277783/5122d178-746d-11e6-87fc-66ff44806239.JPG)

**Comment by nismyi** [comment]
I am having problem on ubuntu16.04 in NS-3.25 version also.

**Comment by kansokusha** [comment]
Building NS-3 LTE module is very time-consuming.
Please give your environment more CPU thread and RAM.
